---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prom
spec:
  values:
    grafana:
      admin:
        existingSecret: grafana-admin-password
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        hosts:
          - grafana.sdsc-dev.k117.org
        tls:
          - hosts:
              - grafana.sdsc-dev.k117.org
            secretName: grafana-tls
    prometheus:
      ingress:
        hosts:
          - prom.sdsc-dev.k117.org
        tls:
          - hosts:
              - prom.sdsc-dev.k117.org
            secretName: prom-tls
